# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf_demo/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2.xci
# IP: The module: 'axi_crossbar_1x2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf_demo/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_crossbar_1x2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf_demo/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2.xci
# IP: The module: 'axi_crossbar_1x2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf_demo/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_crossbar_1x2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
