# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/run_vivado/mycpu_prj1/mycpu.runs/synth_1/soc_axi_lite_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/run_vivado/mycpu_prj1/mycpu.cache/wt [current_project]
set_property parent.project_path C:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/run_vivado/mycpu_prj1/mycpu.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soft/perf_func/obj/allbench/axi_ram.coe
add_files C:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soft/perf_func/obj/bitcount/axi_ram.coe
read_verilog C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/defines2.vh
read_verilog -library xil_defaultlib {
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/utils/adder.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/alu.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/dec/aludec.v
  C:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/rtl/axi_wrap/axi_wrap.v
  C:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/rtl/ram_wrap/axi_wrap_ram.v
  C:/Users/Lenovo/Desktop/colab/axi/bridge_1x2.v
  C:/Users/Lenovo/Desktop/colab/axi/bridge_2x1.v
  C:/Users/Lenovo/Desktop/colab/axi/cache.v
  C:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/rtl/CONFREG/confreg.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/dec/controller.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/exception/cp0_reg.v
  C:/Users/Lenovo/Desktop/colab/axi/cpu_axi_interface.v
  C:/Users/Lenovo/Desktop/colab/axi/d_cache_simple.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/d_sram_to_sram_like.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/datapath.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/utils/div.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/utils/eqcmp.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/exception/exceptdec.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/utils/flopenrc.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/utils/flopr.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/hazard.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/hilo_reg.v
  C:/Users/Lenovo/Desktop/colab/axi/i_cache_simple.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/i_sram_to_sram_like.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/dec/maindec.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/mem_ctrl.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/mips.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/mips_with_sram_like.v
  C:/Users/Lenovo/Desktop/colab/axi/mmu.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/utils/mul.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/utils/mux2.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/utils/mux3.v
  C:/Users/Lenovo/Desktop/colab/axi/mycpu_top.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/pc.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/regfile.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/utils/signext.v
  C:/Users/Lenovo/Desktop/colab/axi/mips_core_with_sram_like/cpu_core/utils/sl2.v
  C:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/rtl/soc_axi_lite_top.v
}
read_ip -quiet C:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_ram/axi_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_ram/axi_ram_ooc.xdc]

read_ip -quiet C:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/clk_pll/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/clk_pll/clk_pll.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/clk_pll/clk_pll_ooc.xdc]

read_ip -quiet C:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter.xci
set_property used_in_synthesis false [get_files -all c:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_ooc.xdc]

read_ip -quiet C:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2.xci
set_property used_in_implementation false [get_files -all c:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/run_vivado/soc_lite.xdc
set_property used_in_implementation false [get_files C:/Users/Lenovo/Desktop/colab/CO-lab-material-CQU/vivado/perf_test_v0.01/soc_axi_perf/run_vivado/soc_lite.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top soc_axi_lite_top -part xc7a100tcsg324-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_axi_lite_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_axi_lite_top_utilization_synth.rpt -pb soc_axi_lite_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
